version: "3"
services:
  mongo-3-4-22:
    image: mongo:3.4.22
    container_name: dapps-mongo-3-4-22
    environment:
        MONGO_INITDB_ROOT_USERNAME: "${MONGODB_INITDB_ROOT_USERNAME}"
        MONGO_INITDB_ROOT_PASSWORD: "${MONGODB_INITDB_ROOT_PASSWORD}"
        TZ: "$TZ"
    volumes:
      - ${DATA_DIR}:/data/db:rw
      - ${DATA_DIR}/mongo_key:/mongo:rw
    ports:
       - "${HOST_PORT}:27017"
    networks:
       - default
    command:
       --auth    