version: "3"
services:
  game-2048:
    image: alexwhen/docker-2048
    container_name: dapps-game-2048
    ports:
      - "${HOST_PORT}:80"
    restart: always
    networks:
      - default

networks:
  default: