version: "3"
services:
  yapi:
    build:
      context: ./
      args:
          YAPI_VERSION: ${YAPI_VERSION}
          YAPI_HOST_PORT: ${YAPI_HOST_PORT}
    ports:
      - "${YAPI_HOST_PORT}:${YAPI_HOST_PORT}"
    volumes:
      - ${YAPI_CONFIG_FILE}:/home/config.json:rw
      - ${YAPI_CONFIG_FILE}:/home/vendors/config.json:rw
      - ${YAPI_LOG_DIR}:/home/log
    depends_on:
      - mongodb-yapi
    cap_add:
      - SYS_PTRACE
    restart: always
    environment:
      TZ: "$TZ"
    networks:
      - default

  mongodb-yapi:
    image: mongo:${MONGODB_VERSION}
    environment:
        MONGO_INITDB_ROOT_USERNAME: "${MONGODB_INITDB_ROOT_USERNAME}"
        MONGO_INITDB_ROOT_PASSWORD: "${MONGODB_INITDB_ROOT_PASSWORD}"
        TZ: "$TZ"
    ports:
       - "${MONGODB_HOST_PORT}:27017"
    networks:
       - default
    command:
       --auth  