version: "3"
services:
  redis5:
    image: redis:5.0.6-alpine
    container_name: dapps-redis5
    ports:
      - "${HOST_PORT}:6379"
    volumes:
      - ${CONF_FILE}:/etc/redis.conf:ro
    restart: always
    entrypoint: ["redis-server", "/etc/redis.conf"]
    environment:
      TZ: "$TZ"
    networks:
      - default