version: "3"
services:
  nextcloud:
    image: nextcloud:latest
    container_name: dapps-nextcloud
    ports:
      - "${HOST_PORT}:80"
    volumes:
      - ${CONF_DIR}:/var/www/html/config
    restart: always
    environment:
      TZ: "$TZ"
    networks:
      - default