version: '3'
services:
  zentao:
    image: idoop/zentao:latest
    container_name: dapps-zentao
    ports:
      - "${HOST_PORT}:80"
    environment:
        TZ: "$TZ"
    volumes:
      - ${SOURCE_DIR}:/opt/zbox/
    restart: always