version: "3"
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: dapps-phpmyadmin
    ports:
      - "${HOST_PORT}:80"
    networks:
      - default
    environment:
      PMA_ARBITRARY: "${PMA_ARBITRARY}"
      TZ: "$TZ"