version: "3"
services:
  mysql57:
    image: mysql:5.7
    container_name: dapps-mysql57
    ports:
      - "${HOST_PORT}:3306"
    volumes:
      - ${CONF_FILE}:/etc/mysql/conf.d/mysql.cnf:ro
      - ${DATA_DIR}:/var/lib/mysql/:rw
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      TZ: "$TZ"    
    networks:
      - default