version: "3"
services:
  mysql-8-0-16:
    image: mysql:8.0.16
    container_name: dapps-mysql-8-0-16
    ports:
      - "${HOST_PORT}:3306"
    volumes:
      - ${CONF_FILE}:/etc/mysql/conf.d/mysql.cnf:ro
      - ${DATA_DIR}:/var/lib/mysql/:rw
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      TZ: "$TZ"    
    networks:
      - default