version: "3"
services:
  nginx116:
    image: nginx:1.16
    container_name: dapps-nginx116
    ports:
      - "${HOST_PORT}:80"
      - "${HTTPS_HOST_PORT}:443"
    volumes:
      - ${SOURCE_DIR}:/var/www/html/:rw
      - ${CONFD_DIR}:/etc/nginx/conf.d/:rw
      - ${CONF_FILE}:/etc/nginx/nginx.conf:ro
      - ${LOG_DIR}:/var/log/nginx/:rw
    restart: always
    environment:
      TZ: "$TZ"    
    networks:
      - default