version: "3"
services:
  rabbitmq37:
    image: rabbitmq:3.7.17-management
    container_name: dapps-rabbitmq37
    ports:
      - "${HOST_PORT}:5672"
      - "${RABBITMQ_HOST_PORT_2}:15672"
    environment:
       RABBITMQ_DEFAULT_USER: "${RABBITMQ_DEFAULT_USER}"
       RABBITMQ_DEFAULT_PASS: "${RABBITMQ_DEFAULT_PASS}"
       TZ: "$TZ"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"   
    restart: always
    networks:
          - default  