version: "3"
services:
  adminmongo:
    image: mrvautin/adminmongo
    container_name: dapps-adminmongo
    ports:
      - "${HOST_PORT}:1234"
    environment:
      HOST: "${HOST}"
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
      TZ: "$TZ"
    networks:
      - default