version: "3"
services:
  gogs:
    image: 'gogs/gogs:latest'
    container_name: dapps-gogs
    ports:
      - "${HOST_PORT_1}:3000"
      - "${HOST_PORT_2}:22"
    volumes:
      - ${SOURCE_DIR}:/data
    networks:
      - default
    environment:
      TZ: "$TZ"
    restart: always

networks:
  default: