version: '3'
services:
  zblog:
    image: 530353222/zblog:1.5.2
    container_name: dapps-zblog
    ports:
      - "${HOST_PORT}:80"
    volumes:
      - ${SOURCE_DIR}:/var/www/html  
    restart: always