version: '3'
services:
  rrshare:
    image: oldiy/rrshare64:latest
    container_name: dapps-rrshare
    ports:
      - "${HOST_PORT}:3001"
    volumes:
      - ${DATA_DIR}:/opt/work/store
    restart: always