version: "3"
services:
  baidupcs-web:
    container_name: dapps-baidupcs-web
    build:
      context: ./
    ports:
      - "${BAIDUPCS_WEB_HOST_PORT}:5299" 
    volumes:
      - ${DOWNLOAD_DIR}:/root/Downloads
    restart: always
    environment:
      TZ: "$TZ"
    networks:
      - default